[project]
name = "textual-pandas"
urls.homepage = "https://github.com/dannywade/textual-pandas"
version = "0.2.3"
description = "A module to build Textual widgets that represent data from the Pandas library"
authors = [{name="Dan Wade", email="danny.wade35@gmail.com"}]
license = "MIT"
readme = "README.md"
requires-python = ">= 3.10"

dependencies =[
"textual<4.0, >=1.0",
"pandas<=2.2.3"]

[project.optional-dependencies]
dev = [
    "pytest>=9.0.2",
    "pytest-asyncio"

]

[dependency-groups]
dev = [
    "ruff>=0.15.9",
]
